config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'frontend/main#index'

  namespace :backend do
    get '/', to: 'main#index'
    resources :products
    resources :categories
    resources :tags
  end

  namespace :frontend do
      get '/', to: 'main#index'
      get 'products', to: 'products#index'
      get 'products/:id', to: 'products#show'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  #validations

  validates :name, :description, :internalCode, :category_id, presence: true
  validates :name, :internalCode, uniqueness: true

  # -- Relations
  has_and_belongs_to_many :tags
  belongs_to :category

  has_one_attached :image

  #scopes
  scope :with_title, ->(title) { where('title LIKE ?', "%#{title}%") }
  scope :with_category, ->(category_id) { where(category_id: category_id) }

  def get_image
   image.attached? ? image : 'missing.png'
  end
end

app/controllers/backend/categories_controller.rb
module Backend
 class CategoriesController < BackendController
  before_action :set_category, only: [:edit, :update, :destroy]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Creado'
      redirect_to backend_categories_path
    else
      flash.now[:alert] = 'Error'
      render :new
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Creado'
      redirect_to backend_categories_path
    else
      flash.now[:alert] = 'Error'
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = 'Eliminado'
    redirect_to backend_categories_path
  end

  def set_category
    @category = Category.find(params[:id])
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
 end
end

app/controllers/backend/main_controller.rb
module Backend
    class MainController < BackendController
        def index; end
    end
end

app/controllers/backend/products_controller.rb
module Backend
 class ProductsController < BackendController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  def index
  #  @presenter = ProductPresenter.new(params)
   @products = Product.paginate(page: params[:page], per_page: 5)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = 'Creado'
      redirect_to backend_products_path
    else
      flash.now[:alert] = 'Error'
      render :new
   end
  end

  def show
    @product = Product.find(params[:id]).decorate
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:notice] = 'Éxito'
      redirect_to [:backend, @product]
    else
      flash.now[:alert] = 'Error'
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:notice] = 'Eliminado'
    redirect_to backend_products_path
  end

  private
  def product_params
    ## strong parameters
    params.require(:product).permit(
      :name,
      :internalCode,
      :category_id,
      :tag_id,
      :praice,
      :cost,
      :description,
      :activo,
      :image
    )
  end

  def set_product
    @product = Product.find(params[:id])
  end
 end
end

app/controllers/backend/tags_controller.rb
module Backend
class TagsController < BackendController
  def index
    @tags = Tag.all
  end

  def new
  @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.new(tag_params)
      if @tag.save
      flash[:notice] = 'Creado'
        redirect_to backend_tags_path
    else
      flash.now[:alert] = 'Error'
      render :new
    end
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      flash.now[:notice] = 'Creado'
    else
      flash.now[:alert] = 'Error'
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash.now[:notice] = 'Eliminado'
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
 end
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController

  before_action :authenticate_user!  

end

app/controllers/frontend/products_controller.rb
module Frontend
 class ProductsController < FrontendController
  def index
    @presenter = ProductsPresenter.new(params)
  end

  def show
    @product = Product.find(params[:id]).decorate
  end

  private
  def product_params
    ## strong parameters
    params.require(:product_filter).permit(:name,:category_id,:image)
  end
 end
end

app/helpers/backend_helper.rb
module BackendHelper

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/backend/products/_form.html.erb
<%= render 'flash_message' %>
<%= form_with model: [:backend, @product], local: true do |f| %>
<div class='card'>
  <div class='card-body'>

    <div class="form-group">
      <%= f.file_field :image %>
    </div>
    <div class="form-group">
      <%= f.label :name, 'Nombre' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :internalCode, 'Codigo' %>
      <%= f.text_field :internalCode, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :category_id, 'Categoria' %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {}, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :activo, 'Activo' %>
      <%= f.check_box :paid %>
    </div>
    <div class="form-group">
      <%= f.label :tag_id, 'Etiqueta' %>
      <%= f.collection_select :tag_ids, Tag.all, :id, :name, {}, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :praice, 'Precio' %>
      <%= f.text_field :praice, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :cost, 'Costo' %>
      <%= f.text_field :cost, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description, 'Descripcion' %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  <div class='card-footer'>
    <%= link_to 'Volver', backend_products_path, class: 'btn btn-outline-secondary' %>
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
</div>

<!-- IMAGENES -->

<% end %>

app/views/backend/products/_product.html.erb
<tr>
  <td><%= image_tag product.image if product.image.attached? %></td>
  <td><%= product.name %></td>
  <td><%= product.active %></td>
  <td><%= product.praice %></td>
  <td> tag.name </td>
  <td class='text-right'>
    <%= link_to 'Ver', backend_product_path(product), class: 'btn btn-success' %>
    <%= link_to 'Editar', edit_backend_product_path(product), class: 'btn btn-success' %>
    <%= link_to 'Borrar', backend_product_path(product), method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/backend/products/edit.html.erb
<div class="container">
    <p> <br>Editar un producto </br> </p>
    <%= render 'form' %>
</div>

app/views/backend/products/index.html.erb
<h1 class='mt-2'>Productos</h1>
<%= render 'flash_message' %>

<table class="table table-bordered">
  <thead class="thead-light">
    <tr>
      <th> Imagen </th>
      <th>Producto</th>
      <th>Activo</th>
      <th>Precio</th>
      <th>Eiquetas</th>
      <th class='text-right'><%= link_to 'Nuevo Producto', new_backend_product_path, class: 'btn btn-dark' %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @products %>
  </tbody>
</table>

<%= will_paginate @products %>

app/views/backend/products/new.html.erb
<div class="container">
    <p> <br>Ingresar nuevo producto </br> </p>
    <%= render 'form' %>
</div>

app/views/backend/products/show.html.erb
<h1>Detalle de producto</h1>

<div class='card'>
  <div class='card-body'>
    <div class="mb-3">
      <b>Nombre: </b> <%= @product.name %><br/>
    </div>
    <div class="mb-3">
      <b>Codigo Interno: </b> <%= @product.internalCode %> <br/>
    </div>
    <div class="mb-3">
      <b>Precio: </b> <%= @product.praice %> <br/>
    </div>
    <div class="mb-3">
      <b>Costo: </b> <%= @product.cost %> <br/>
    </div>
    <div class="mb-3">
      <b>Categoria: </b> <%= @product.category&.name %> <br/>
    </div>
      <div class="mb-3">
      <b>Contenido: </b> <%= @product.description %> <br/>
    </div>
  
  </div>
  <div class='card-footer'>
    <%= link_to 'Volver', backend_products_path, class: 'btn btn-outline-secondary' %>
  </div>
</div>