config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'frontend/main#index'

  namespace :backend do
    get '/', to: 'main#index'
    resources :products
    resources :categories
    resources :tags
  end

  namespace :frontend do
      get '/', to: 'main#index'
      get 'products', to: 'products#index'
      get 'products/:id', to: 'products#show'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  # -- Validations
 validates :name, presence: true, uniqueness: true

 #Relations
 has_many :products

end

app/controllers/backend/categories_controller.rb
module Backend
 class CategoriesController < BackendController
  before_action :set_category, only: [:edit, :update, :destroy]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Creado'
      redirect_to backend_categories_path
    else
      flash.now[:alert] = 'Error'
      render :new
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Creado'
      redirect_to backend_categories_path
    else
      flash.now[:alert] = 'Error'
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = 'Eliminado'
    redirect_to backend_categories_path
  end

  def set_category
    @category = Category.find(params[:id])
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
 end
end

app/controllers/backend/main_controller.rb
module Backend
    class MainController < BackendController
        def index; end
    end
end

app/controllers/backend/products_controller.rb
module Backend
 class ProductsController < BackendController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  def index
  #  @presenter = ProductPresenter.new(params)
   @products = Product.paginate(page: params[:page], per_page: 5)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = 'Creado'
      redirect_to backend_products_path
    else
      flash.now[:alert] = 'Error'
      render :new
   end
  end

  def show
    @product = Product.find(params[:id]).decorate
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:notice] = 'Éxito'
      redirect_to [:backend, @product]
    else
      flash.now[:alert] = 'Error'
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:notice] = 'Eliminado'
    redirect_to backend_products_path
  end

  private
  def product_params
    ## strong parameters
    params.require(:product).permit(
      :name,
      :internalCode,
      :category_id,
      :tag_id,
      :praice,
      :cost,
      :description,
      :activo,
      :image
    )
  end

  def set_product
    @product = Product.find(params[:id])
  end
 end
end

app/controllers/backend/tags_controller.rb
module Backend
class TagsController < BackendController
  def index
    @tags = Tag.all
  end

  def new
  @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.new(tag_params)
      if @tag.save
      flash[:notice] = 'Creado'
        redirect_to backend_tags_path
    else
      flash.now[:alert] = 'Error'
      render :new
    end
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      flash.now[:notice] = 'Creado'
    else
      flash.now[:alert] = 'Error'
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash.now[:notice] = 'Eliminado'
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
 end
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController

  before_action :authenticate_user!  

end

app/helpers/backend_helper.rb
module BackendHelper

end

app/views/backend/categories/_category.html.erb
<tr>
  <td>
    <%= category.name %>
  </td>
  <td class='text-right'>
    <%= link_to 'Editar', edit_backend_category_path(category), class: 'btn btn-success' %>
    <%= link_to 'Borrar', backend_category_path(category), method: :delete, data: { confirm: 'Esta seguro?' }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/backend/categories/_form.html.erb
<%= render 'flash_message' %>

<%= form_with model: [:backend,@category], local: true do |f| %>
<div class='card'>
  <div class='card-body'>
    <div class="form-group">
      <%= f.label :name, 'Nombre' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

  <div class='card-footer'>
    <%= link_to 'Volver', backend_categories_path, class: 'btn btn-outline-secondary' %>
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/backend/categories/edit.html.erb
<h1 class='mt-2'>Editar categoria #<%= @category.id %></h1>
<%= render 'form' %>

app/views/backend/categories/index.html.erb
<h1 class='mt-2'>Categorias</h1>
<%= render 'flash_message' %>

<table class="table table-bordered">
  <thead class="thead-light">
    <tr>
      <th>Nombre</th>
      <th class='text-right'><%= link_to 'Nueva Categoria', new_backend_category_path, class: 'btn btn-dark' %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @categories %>
  </tbody>
</table>

app/views/backend/categories/new.html.erb
<h1 class='mt-2'>Nueva categoria</h1>
<%= render 'form' %>