config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'frontend/main#index'

  namespace :backend do
    get '/', to: 'main#index'
    resources :products
    resources :categories
    resources :tags
  end

  namespace :frontend do
      get '/', to: 'main#index'
      get 'products', to: 'products#index'
      get 'products/:id', to: 'products#show'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_flash_class(key)
    case key.to_sym
    when :notice
      'success'
    when :alert
      'danger'
  end
end
end

app/views/application/_flash_message.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
 <!-- Brand -->
 <a class="navbar-brand" href="#">Logo</a>

 <!-- Links -->
 <ul class="navbar-nav">
   <li class="nav-item">
     <a class="nav-link" href="#">Link 1</a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="#">Link 2</a>
   </li>

   <!-- Dropdown -->
   <li class="nav-item dropdown">
     <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
       Dropdown link
     </a>
     <div class="dropdown-menu">
       <a class="dropdown-item" href="#">Link 1</a>
       <a class="dropdown-item" href="#">Link 2</a>
       <a class="dropdown-item" href="#">Link 3</a>
     </div>
   </li>
   <% if user_signed_in? %>
   <li>
     <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
   </li>
   <%end%>
 </ul>
</nav>

app/views/application/_sidebar.html.erb
<div class="bg-light border-right" id="sidebar-wrapper">
  <div class="sidebar-heading">Catálogo</div>
  <div class="list-group list-group-flush">
    <%= link_to 'Productos', backend_products_path, class: 'list-group-item list-group-item-action bg-light' %>
    <%= link_to 'Categorias', backend_categories_path, class: 'list-group-item list-group-item-action bg-light' %>
    <%= link_to 'Tags', backend_tags_path, class: 'list-group-item list-group-item-action bg-light' %>
    <%= link_to 'Usuarios', backend_categories_path, class: 'list-group-item list-group-item-action bg-light' %>
    <%= link_to 'Configuración Web', backend_categories_path, class: 'list-group-item list-group-item-action bg-light' %>
  </div>
</div>